namespace: kubesphere-logging-system
namePrefix: kube-events-
resources:
- crd
- rbac
- operator
configurations:
- kustomizeconfig.yaml
images:
- name: operator
  newName: kubesphere/kube-events-operator
  newTag: v0.1.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
