namespace: kubesphere-logging-system
namePrefix: kube-events-
resources:
- cluster-rules-default.yaml
- exporter.yaml
- ruler.yaml
configurations:
- kustomizeconfig.yaml
patchesStrategicMerge:
- ruler_patch.yaml
images:
- name: exporter
  newName: kubesphere/kube-events-exporter
  newTag: 0.5.0
- name: ruler
  newName: kubesphere/kube-events-ruler
  newTag: 0.5.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
