namespace:
- path: spec/sinks/webhooks/service/namespace
  kind: Exporter

namePrefix:
- path: spec/sinks/webhooks/service/name
  kind: Exporter

images:
- path: spec/image
  kind: Exporter
- path: spec/image
  kind: Ruler
